#! /bin/sh

bspc monitor eDP1 -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'
#bspc monitor -d '' '' '' '' '' '' '' '' '' ''
bspc monitor HDMI2 -d 'MON'

bspc config border_width          2
bspc config normal_border_color   "#446677"
bspc config active_border_color   "#ff9922"
bspc config focused_border_color  "#aeebee"
bspc config presel_feedback_color "#446677"
bspc config window_gap            20
bspc config split_ratio           0.5 #547
bspc config borderless_monocle    true
bspc config gapless_monocle       true
#bspc config focus_follows_pointer true

bspc rule -a "Scratchpad-st" state=floating sticky=on hidden=on
bspc rule -a "Vimnotes-st" state=floating sticky=on
bspc rule -a "Gimp" desktop='^6'
bspc rule -a "Brave-browser" desktop='^2'
bspc rule -a "Firefox" desktop='^2'
bspc rule -a "firefox-esr" desktop='^2'
bspc rule -a "TelegramDesktop" desktop='^3'
bspc rule -a "Cinelerra" state=floating
bspc rule -a "Zathura" state=tiled

sxhkd &
brillo -I
pipewire &
feh --no-fehbg --bg-fill $HOME/.config/shanghai.jpg &
polybar bar &
redshift -l 41:28 -t 6500:3700 &
picom -bcf &
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
xset r rate 300 100
xset b off
xset s off
xset s noblank
xset -dpms
#xinput set-prop 12 'libinput Accel Speed' -0.3
setxkbmap -layout tr
setxkbmap -option caps:escape
#xmodmap -e "keycode 66 = Escape"
#urxvt -name urxvt-scratch &
st -c Scratchpad-st &
